version: "3.9"

########################### NETWORKS
# Create traefik network
# docker network create traefik

networks:
  traefik:
    external: true

########################### SERVICES
services:
  ############################# TRAEFIK

  # Traefik 3 - Reverse Proxy

  traefik:
    image: traefik:v3.0
    container_name: traefik
    hostname: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - 80:80
      - 443:443
      - 6379:6379
      - 3306:3306
      - 5432:5432
    networks:
      - traefik
    labels:
      #- "autoheal=true"
      - traefik.enable=true
      # HTTP-to-HTTPS Redirect
      - traefik.http.routers.http-catchall.entrypoints=http
      - traefik.http.routers.http-catchall.rule=HostRegexp(`{host:.+}`)
      - traefik.http.routers.http-catchall.middlewares=redirect-to-https
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      # HTTP Routers
      - traefik.http.routers.traefik-rtr.entrypoints=https
      - traefik.http.routers.traefik-rtr.rule=Host(`traefik.${DOMAINNAME?Variable not set}`)
      - traefik.http.routers.traefik-rtr.tls.domains[0].main=${DOMAINNAME?Variable not set}
      - traefik.http.routers.traefik-rtr.tls.domains[0].sans=*.${DOMAINNAME?Variable not set}
      ## Services - API
      - traefik.http.routers.traefik-rtr.service=api@internal
      ## Healthcheck/ping
      # - traefik.http.routers.ping.rule=Host(`traefik.$DOMAINNAME`) && Path(`/ping`)
      # - traefik.http.routers.ping.tls=true
      # - traefik.http.routers.ping.service=ping@internal
      ## Middlewares
      - traefik.http.routers.traefik-rtr.middlewares=traefik-auth
      - traefik.http.middlewares.traefik-auth.basicauth.usersfile=/.htpasswd
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs/:/etc/traefik/certs/:ro
      - ./traefik.yml:/traefik.yml:ro
      - ./conf/:/etc/traefik/conf/:ro
      - ./.htpasswd:/.htpasswd:ro
      - ./data/logs:/logs:rw
    env_file:
      - .env
