version: "3.9"

services:
  traefik:
    image: traefik:v3.0
    container_name: traefik
    hostname: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - 80:80
      - 443:443
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.constraint-label=traefik-proxied
      - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
      - traefik.http.routers.traefik-proxied-http.rule=Host(`${DOMAIN?Variable not set}`)
      - traefik.http.routers.traefik-proxied-http.entrypoints=web
      - traefik.http.routers.traefik-proxied-http.middlewares=https-redirect
      - traefik.http.routers.traefik-proxied-https.rule=Host(`${DOMAIN?Variable not set}`)
      - traefik.http.routers.traefik-proxied-https.entrypoints=websecure
      - traefik.http.routers.traefik-proxied-https.tls=true
      - traefik.http.routers.traefik-proxied-https.service=api@internal
      - traefik.http.routers.api.middlewares=auth
      - traefik.http.middlewares.auth.basicauth.users=${USERNAME?Variable not set}:${HASHED_PASSWORD?Variable not set}
      - traefik.http.services.traefik-proxied.loadbalancer.server.port=8080
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs/:/etc/traefik/certs/:ro
      - ./traefik.yml:/traefik.yml:ro
      - ./conf/:/etc/traefik/conf/:ro
    env_file:
      - .env

networks:
  traefik:
    external: true
