log:
  level: ERROR

entryPoints:
  http:
    address: :80
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: :443
  redis:
    address: :6379
  postgres:
    address: :5432
  mariadb:
    address: :3306

providers:
  docker:
    endpoint: unix:///var/run/docker.sock
    exposedByDefault: false
    network: traefik
    watch: true
  file:
    directory: /etc/traefik/conf
    watch: true

api:
  insecure: false
  debug: true
  dashboard: true
